version: "3"
services: 
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    volumes:
      - /Users/Shared/data/postgresql-dev:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    env_file:
      - ./.env.local
