import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.scss"
import { PropsWithChildren } from "react"
import ReactQueryProvider from "./_components/ReactQueryBoundry"
import ReduxProvider from "./_components/ReduxProvider"

type RootLayoutProps = PropsWithChildren

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
